import { Participant, PollCategory } from './types'

export const PARTICIPANTS: Participant[] = [
  { id: 'p-12', name: 'Messier', bio: 'AI engineer & creative technologist. Music producer. Chaos architect.', photo_url: '/avatars/messier.jpg', socials: { twitter: 'rssmrm', instagram: 'mara.ipynb', website: 'https://messier-systems.vercel.app/', bandcamp: 'https://mmessier.bandcamp.com/music' } },
  { id: 'p-40', name: 'Kat (the vat)', bio: 'Multi-disciplinary creator, 25. Into ARGs, DAOs, networked organisms. Video editor, IRL streamer.', photo_url: '/avatars/kat.jpg', socials: { youtube: 'https://youtu.be/j4d1a2H_FHE' } },
  { id: 'p-1', name: 'Emily', bio: 'From Bristol, UK. AI Safety Camp alum, TTRPG designer, content creator.', photo_url: '/avatars/emily.png', socials: { youtube: 'https://www.youtube.com/@FrodgePodge1398', website: 'https://thetreacherousturn.ai' } },
  { id: 'p-2', name: 'Evan', bio: 'From Ontario, Canada. CS student, curator of fashion, music and philosophical ideas.', photo_url: '', socials: {} },
  { id: 'p-3', name: 'Ana', bio: 'Temple University, studying Film & Media Arts. Filmmaker, animator, game developer.', photo_url: '/avatars/ana.png', socials: { youtube: 'https://www.youtube.com/@TheCrowdProductions', website: 'https://anakitten.itch.io/mario-kart-gb' } },
  { id: 'p-4', name: 'Michelle Huang', bio: 'Artist-researcher running an art collective nonprofit in rural Japan.', photo_url: '/avatars/michelle_huang.jpg', socials: { twitter: 'michellehuang42', website: 'https://michellekhuang.com/' } },
  { id: 'p-5', name: 'Matthew', bio: 'From Sydney, Australia. Uni student and PDKU player.', photo_url: '/avatars/matthew.jpg', socials: { instagram: 'matthew4244_', youtube: 'https://youtube.com/shorts/04voHXnLghY' } },
  { id: 'p-6', name: 'Savannah', bio: 'Based in Las Vegas. Short films, paintings, photography on mental health and AI ethics.', photo_url: '/avatars/savannah.jpg', socials: { instagram: 'savannah_raisor', website: 'https://savannahraisor.com/' } },
  { id: 'p-7', name: 'Becka', bio: 'From Philadelphia. Yoga teacher, singing teacher. Making AI content for non-technical audiences.', photo_url: '', socials: {} },
  { id: 'p-8', name: 'Tyler Alterman', bio: 'Based in NYC. Novelist, contact improv dancer, community builder at Fractal NYC.', photo_url: '/avatars/tyler.jpg', socials: { website: 'http://tyleralterman.com' } },
  { id: 'p-9', name: 'Eugene', bio: 'Social butterfly, 23. Into nuance, behavioral biology, and fighting for people left behind.', photo_url: '/avatars/eugene.jpg', socials: { instagram: 'eugene_affirmative' } },
  { id: 'p-10', name: 'Aaron Silverbook', bio: '', photo_url: '/avatars/aaron.jpg', socials: { website: 'http://AaronSilverbook.com' } },
  { id: 'p-11', name: 'KT', bio: 'Based in Budapest. Human psychology, group dynamics. Cozy introvert vibes.', photo_url: '', socials: {} },
  { id: 'p-13', name: 'Isabel', bio: 'From Australia, based in Singapore. Creative technologist. Built napole0n.ai.', photo_url: '/avatars/isabel.jpg', socials: { instagram: 'artificial.isabel', website: 'https://napole0n.ai' } },
  { id: 'p-14', name: 'Jessiah', bio: 'From Mendocino, CA. Former English lit teacher, now data science. Life coach and basketball coach.', photo_url: '/avatars/jessiah.jpg', socials: { instagram: 'jamellott23', website: 'http://gensilverjess.com' } },
  { id: 'p-15', name: 'Avisha', bio: 'Based in NY. Signal processing + AI dev. Runs @distilledscience for science education.', photo_url: '/avatars/avisha.jpg', socials: { instagram: 'distilledscience' } },
  { id: 'p-16', name: 'Francesca (Pixel Surfer)', bio: 'Based in San Diego. Ex-Microsoft SWE, musician, surfer/surfboard shaper.', photo_url: '/avatars/francesca.jpg', socials: { substack: 'https://pixelsurfer.substack.com/', music: 'https://distrokid.com/hyperfollow/pixelsurfer/belonging' } },
  { id: 'p-17', name: 'Eliana', bio: 'USC acting alum from West LA. Singer, Ableton user, stand-up comedian.', photo_url: '/avatars/eliana.jpg', socials: { twitter: 'yellieyana' } },
  { id: 'p-18', name: 'Elwyn', bio: 'From Florida. Former comedy video creator. Mindful content for positive pattern-making.', photo_url: '', socials: {} },
  { id: 'p-19', name: 'Justin Kuiper', bio: 'From Sacramento. Scriptwriter for Game Theory (~1B views). Now doing Substack + YouTube.', photo_url: '/avatars/justin.png', socials: { substack: 'https://justinkuiper.substack.com/', youtube: 'https://www.youtube.com/@ProofPositiveShow', letterboxd: 'https://letterboxd.com/JustKuiper/' } },
  { id: 'p-20', name: 'Michelle (mee-chell)', bio: 'From Mexico, now in Sedona, AZ. Cognitive science (consciousness), pursuing MA/MFA at CIIS.', photo_url: '', socials: {} },
  { id: 'p-21', name: 'Tonchi', bio: 'From Santiago, Chile. 19yo law student, STEM activist. Nickelodeon Kids\' Choice Award winner.', photo_url: '/avatars/tonchi.jpg', socials: { instagram: 'tonchimatta' } },
  { id: 'p-22', name: 'Brenda', bio: 'From Costa Rica, now in California. Lives in a hacker house. AI for women\'s health.', photo_url: '', socials: {} },
  { id: 'p-23', name: 'Gai', bio: 'From Japan, at a hippie commune in West County, CA. Traveler, hitchhiker, 2D animator.', photo_url: '/avatars/gai.png', socials: { youtube: 'https://m.youtube.com/@micrawstudio/videos' } },
  { id: 'p-24', name: 'Aryeh', bio: 'Based in Columbus, OH. Fishtank Season 4 alum, aspiring video essayist.', photo_url: '/avatars/aryeh.jpg', socials: { twitter: 'R_YayOFFICIAL', instagram: 'r_yayofficial', youtube: 'https://www.youtube.com/watch?v=s-gHyWm5Ggk' } },
  { id: 'p-25', name: 'Glasha', bio: 'Lives in Buffalo, NY. From Moscow. Philosophy grad, EA, AI risk communications.', photo_url: '/avatars/glasha.jpg', socials: { substack: 'https://romansattic.substack.com/' } },
  { id: 'p-26', name: 'Charlie Guthmann', bio: 'From Chicago, lives in Philly. Econ/AI/progress studies lab. Biking Chicago to PDKU interviewing people about AI.', photo_url: '/avatars/charlie.png', socials: { instagram: 'charlie.guthmann', youtube: 'https://www.youtube.com/@charlieguthmann2531' } },
  { id: 'p-27', name: 'Christian Gonzalez', bio: 'From NJ, lived in Barcelona and Montreal. Physics, philosophy, ML. Philosophy podcast host.', photo_url: '/avatars/christian.jpg', socials: { twitter: 'cxgonzalez', youtube: 'https://www.youtube.com/watch?v=WX8ZRbvN2N8' } },
  { id: 'p-28', name: 'Aron Fromm', bio: 'From LA. Entertainment/animation creator. Worked on "Smiling Friends". Restores old animatronics.', photo_url: '/avatars/aron.jpg', socials: { twitter: 'aronfromm', youtube: 'https://youtu.be/1kHWG9fGNQw' } },
  { id: 'p-29', name: 'Jeredino Lavagnino', bio: 'Retired blogger, aspiring video creator. Werner Herzog fan. Literary criticism & anime reviews.', photo_url: '/avatars/jeredino.jpg', socials: { substack: 'https://zatsuon.substack.com/', website: 'https://suboptimalism.neocities.org/' } },
  { id: 'p-30', name: 'Halina', bio: 'Born and raised in the Bay Area. Blockchain, decentralized governance. 70k followers.', photo_url: '/avatars/halina.jpg', socials: { twitter: 'halina_eth' } },
  { id: 'p-31', name: 'Josie', bio: 'Mexican-American from Alabama, based in Malaysia. Ex-software dev, content creator.', photo_url: '/avatars/josie.jpg', socials: { instagram: 'josiefiguresitout' } },
  { id: 'p-32', name: 'Caitlin Yardley', bio: 'Based in London, from Canada. AI Safety comms (BlueDot, FLI). Posts as FutureBriefing.', photo_url: '/avatars/caitlin_y.jpg', socials: { twitter: 'YardleyCaitlin', instagram: 'futurebriefing' } },
  { id: 'p-33', name: 'Tess', bio: 'Lives in Berkeley. Gap year after Stanford PhD in civil engineering. Pivoting to AI safety.', photo_url: '/avatars/tess.jpg', socials: { twitter: 'thegartsy' } },
  { id: 'p-34', name: 'Tanner', bio: 'Geologist from Appalachian Ohio. Master\'s in paleoriver systems. Former Geometry Dash YouTuber.', photo_url: '/avatars/tanner.jpg', socials: { youtube: 'https://www.youtube.com/channel/UCbAOw00ldX5Gnb47e9SYqZg', substack: 'https://open.substack.com/pub/kenorland' } },
  { id: 'p-35', name: 'Oliver', bio: 'Based in LA. 3D motion graphics about AI, submits shorts to film festivals.', photo_url: '/avatars/oliver.jpg', socials: { youtube: 'https://youtu.be/E9763olM5tk' } },
  { id: 'p-36', name: 'Brogan (Art Chad)', bio: 'YouTuber from Toronto. Video essays about art, culture, and tech. Runs the CCCRU studio.', photo_url: '/avatars/brogan.jpg', socials: { youtube: 'https://m.youtube.com/watch?v=aECSgXr5-hY' } },
  { id: 'p-37', name: 'Caitlin (Has Questions)', bio: 'Farm kid from Michigan. Music education, opera, former creative director for a US Senator. Starting Georgetown.', photo_url: '/avatars/caitlin_q.png', socials: { youtube: 'https://www.youtube.com/@CaitlinHasQuestions/shorts' } },
  { id: 'p-38', name: 'John (Broomhead)', bio: 'From San Francisco. Eco-luddite turned tech optimist, AI safety via climate policy. Classical singer.', photo_url: '', socials: {} },
  { id: 'p-39', name: 'Josh', bio: 'Founded UBC AI safety group. AI governance research, now making TikToks about AI safety.', photo_url: '/avatars/josh.jpg', socials: { instagram: 'joshthor_', website: 'http://ubcaisafety.org' } },
  { id: 'p-41', name: 'Camden', bio: 'Based in Boston, 23. CS grad. Music producer (hyperpop/math-rock/metal), theater, improv.', photo_url: '/avatars/camden.jpg', socials: { instagram: 'camdenwyeth', youtube: 'https://youtu.be/iovJpHcXlxQ' } },
  { id: 'p-43', name: 'Loan (DD)', bio: 'From Vietnam, based in Seattle. ML forecasting at Google/Apple. 3D printing, yoga, aerial.', photo_url: '', socials: {} },
]

export const POLL_CATEGORIES: PollCategory[] = [
  { id: 'fan-favorite', name: 'Fan Favorite', slug: 'fan-favorite', description: "Who's your #1 overall?", icon: '⭐', colorClass: 'poll-fan-favorite' },
  { id: 'most-entertaining', name: 'Most Entertaining', slug: 'most-entertaining', description: "Who's been the most fun to follow?", icon: '🎭', colorClass: 'poll-most-entertaining' },
  { id: 'most-likely-to-win', name: 'Most Likely to Win', slug: 'most-likely-to-win', description: 'Who do you think takes it all?', icon: '🏆', colorClass: 'poll-most-likely-to-win' },
  { id: 'best-vibes', name: 'Best Vibes', slug: 'best-vibes', description: 'The ultimate vibe check winner', icon: '✨', colorClass: 'poll-best-vibes' },
  { id: 'best-dressed', name: 'Best Dressed', slug: 'best-dressed', description: 'Serving looks on the daily', icon: '👗', colorClass: 'poll-best-dressed' },
  { id: 'worst-dressed', name: 'Worst Dressed', slug: 'worst-dressed', description: 'Fashion crimes against humanity', icon: '🧦', colorClass: 'poll-worst-dressed' },
  { id: 'most-chaotic', name: 'Most Chaotic', slug: 'most-chaotic', description: 'Pure unfiltered chaos energy', icon: '🔥', colorClass: 'poll-most-chaotic' },
  { id: 'god-empress', name: 'Most Likely to Seduce the Basilisk', slug: 'god-empress', description: 'And become god empress, obviously', icon: '👑', colorClass: 'poll-god-empress' },
]

export const NEON_COLORS = [
  '#1fc4ff', '#ff1fb8', '#fbec14', '#b026ff', '#14f0b0', '#14ffd2',
  '#ff6b35', '#ff1f1f', '#7b61ff', '#00ff88',
]
